# Generated by Django 5.2.7 on 2026-01-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0003_googleoauthconfig_usercredential_auth_provider_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.DeleteModel(
            name='GoogleOAuthConfig',
        ),
    ]
