# Generated by Django 5.2.7 on 2026-01-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlapi', '0006_modelcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelcomment',
            name='user_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
